application: hchaps
version: 0-0-pre
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.application
- url: /index\.html
  script: main.application
- url: /static
  static_dir: static
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: django
  version: latest
