application: hchaps
version: 0-0-pre
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /index\.html
  script: main.py
- url: /static
  static_dir: static
- url: /.*
  script: main.py
